import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import {
  signIn, 
  signOut,
  useSession
} from 'next-auth/client';
import Link from 'next/link';
import { connectToDatabase } from '../util/mongodb'
import { IoLogoFacebook, IoLogoInstagram } from "react-icons/io"
import { signIn, signOut, useSession } from 'next-auth/client'

  
export default function Home({ isConnected }) {
    const [ session, loading ] = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Cutie Hack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {!session && <>
          Not signed in <br/>
          <button onClick={() => signIn()}>Sign in</button>
        </>}
        {session && <>
          Signed in as {session.user.email} <br/>
          <button onClick={() => signOut()}>Sign out</button>
        </>}

        {/* {isConnected ? (
          <h2 className="subtitle">You are connected to MongoDB</h2>
        ) : (
          <h2 className="subtitle">
            You are NOT connected to MongoDB. Check the <code>README.md</code>{' '}
            for instructions.
          </h2>
        )}    */}
      
        {!session && <>
          <h1>You are not signed in</h1> <br/>
          <button onClick={signIn}>Sign in</button>
        </>}

        {session && <>
          <h1>Signed in as {session.user.name} </h1> <br/>
          <h1 className={styles.subtitle}>
          Welcome to
          </h1>
          <h1 className={styles.title}>
            Cutie Hack
          </h1>
          <p className={styles.description}>
            Coming Soon...
          </p>
            <button onClick={signOut}>Sign out</button>
        </>}

        

        <div className={styles.grid}>
          <a 
            href="https://www.facebook.com/cutiehack/"
            className={styles.card}
          >
            <div className={styles.textIconWrapper}>
              <div>Facebook</div>
              <IoLogoFacebook className={styles.icon}/>
            </div>
          </a>

          <a 
            href="https://www.instagram.com/cutiehack_ucr/"
            className={styles.card}
          >
            <div className={styles.textIconWrapper}>
              <div>Instagram</div>
              <IoLogoInstagram className={styles.icon}/>
            </div>
          </a>
        </div>
        </main>

      <footer className={styles.footer}>
        Click the links above to learn more about us!
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const { client } = await connectToDatabase()

  const isConnected = await client.isConnected()

  return {
    props: { isConnected },
  }
}