import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { connectToDatabase } from '../util/mongodb'
import { IoLogoFacebook, IoLogoInstagram, IoLogoTwitter, IoLogoLinkedin } from "react-icons/io"

export default function Home({ isConnected }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cutie Hack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.subtitle}>
          Welcome to
        </h1>
        <h1 className={styles.title}>
          Cutie Hack
        </h1>
        <p className={styles.description}>
          Coming Soon...
        </p>

        {/* {isConnected ? (
          <h2 className="subtitle">You are connected to MongoDB</h2>
        ) : (
          <h2 className="subtitle">
            You are NOT connected to MongoDB. Check the <code>README.md</code>{' '}
            for instructions.
          </h2>
        )} */}

        <div className={styles.grid}>
          <a 
            href=""
            className={styles.card}
          >
            <div className={styles.textIconWrapper}>
              <div>Facebook</div>
              <IoLogoFacebook className={styles.icon}/>
            </div>
          </a>

          <a 
            href=""
            className={styles.card}
          >
            <div className={styles.textIconWrapper}>
              <div>Instagram</div>
              <IoLogoInstagram className={styles.icon}/>
            </div>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <div className={styles.textIconWrapper}>
              <div>Twitter</div>
              <IoLogoTwitter className={styles.icon}/>
            </div>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <div className={styles.textIconWrapper}>
              <div>Linkedin</div>
              <IoLogoLinkedin className={styles.icon}/>
            </div>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Click the links above to learn more about us!
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  const { client } = await connectToDatabase()

  const isConnected = await client.isConnected()

  return {
    props: { isConnected },
  }
}